//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alive.Test.CommunicationServer.Communication {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.lionth.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.lionth.com/", ConfigurationName="Communication.CommunicationServiceSoap")]
    public interface CommunicationServiceSoap {
        
        // CODEGEN: Generating message contract since element name pipeName from namespace http://www.lionth.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lionth.com/SendMessage", ReplyAction="*")]
        Alive.Test.CommunicationServer.Communication.SendMessageResponse SendMessage(Alive.Test.CommunicationServer.Communication.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name groupName from namespace http://www.lionth.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lionth.com/SendMessageToGroup", ReplyAction="*")]
        Alive.Test.CommunicationServer.Communication.SendMessageToGroupResponse SendMessageToGroup(Alive.Test.CommunicationServer.Communication.SendMessageToGroupRequest request);
        
        // CODEGEN: Generating message contract since element name pipeName from namespace http://www.lionth.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lionth.com/GetMessage", ReplyAction="*")]
        Alive.Test.CommunicationServer.Communication.GetMessageResponse GetMessage(Alive.Test.CommunicationServer.Communication.GetMessageRequest request);
        
        // CODEGEN: Generating message contract since element name pipeName from namespace http://www.lionth.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lionth.com/Register", ReplyAction="*")]
        Alive.Test.CommunicationServer.Communication.RegisterResponse Register(Alive.Test.CommunicationServer.Communication.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name pipeName from namespace http://www.lionth.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lionth.com/RegisterWithGroup", ReplyAction="*")]
        Alive.Test.CommunicationServer.Communication.RegisterWithGroupResponse RegisterWithGroup(Alive.Test.CommunicationServer.Communication.RegisterWithGroupRequest request);
        
        // CODEGEN: Generating message contract since element name pipeName from namespace http://www.lionth.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lionth.com/SignOff", ReplyAction="*")]
        Alive.Test.CommunicationServer.Communication.SignOffResponse SignOff(Alive.Test.CommunicationServer.Communication.SignOffRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Alive.Test.CommunicationServer.Communication.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pipeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string pipeName, string message) {
            this.pipeName = pipeName;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Alive.Test.CommunicationServer.Communication.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(bool SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageToGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageToGroup", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.SendMessageToGroupRequestBody Body;
        
        public SendMessageToGroupRequest() {
        }
        
        public SendMessageToGroupRequest(Alive.Test.CommunicationServer.Communication.SendMessageToGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class SendMessageToGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public SendMessageToGroupRequestBody() {
        }
        
        public SendMessageToGroupRequestBody(string groupName, string message) {
            this.groupName = groupName;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageToGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageToGroupResponse", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.SendMessageToGroupResponseBody Body;
        
        public SendMessageToGroupResponse() {
        }
        
        public SendMessageToGroupResponse(Alive.Test.CommunicationServer.Communication.SendMessageToGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class SendMessageToGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMessageToGroupResult;
        
        public SendMessageToGroupResponseBody() {
        }
        
        public SendMessageToGroupResponseBody(int SendMessageToGroupResult) {
            this.SendMessageToGroupResult = SendMessageToGroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessage", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.GetMessageRequestBody Body;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(Alive.Test.CommunicationServer.Communication.GetMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class GetMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pipeName;
        
        public GetMessageRequestBody() {
        }
        
        public GetMessageRequestBody(string pipeName) {
            this.pipeName = pipeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageResponse", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.GetMessageResponseBody Body;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(Alive.Test.CommunicationServer.Communication.GetMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class GetMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Alive.Test.CommunicationServer.Communication.ArrayOfString GetMessageResult;
        
        public GetMessageResponseBody() {
        }
        
        public GetMessageResponseBody(Alive.Test.CommunicationServer.Communication.ArrayOfString GetMessageResult) {
            this.GetMessageResult = GetMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(Alive.Test.CommunicationServer.Communication.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pipeName;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string pipeName) {
            this.pipeName = pipeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(Alive.Test.CommunicationServer.Communication.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterResponseBody {
        
        public RegisterResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterWithGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterWithGroup", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.RegisterWithGroupRequestBody Body;
        
        public RegisterWithGroupRequest() {
        }
        
        public RegisterWithGroupRequest(Alive.Test.CommunicationServer.Communication.RegisterWithGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class RegisterWithGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pipeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string groupName;
        
        public RegisterWithGroupRequestBody() {
        }
        
        public RegisterWithGroupRequestBody(string pipeName, string groupName) {
            this.pipeName = pipeName;
            this.groupName = groupName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterWithGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterWithGroupResponse", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.RegisterWithGroupResponseBody Body;
        
        public RegisterWithGroupResponse() {
        }
        
        public RegisterWithGroupResponse(Alive.Test.CommunicationServer.Communication.RegisterWithGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterWithGroupResponseBody {
        
        public RegisterWithGroupResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignOffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignOff", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.SignOffRequestBody Body;
        
        public SignOffRequest() {
        }
        
        public SignOffRequest(Alive.Test.CommunicationServer.Communication.SignOffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lionth.com/")]
    public partial class SignOffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pipeName;
        
        public SignOffRequestBody() {
        }
        
        public SignOffRequestBody(string pipeName) {
            this.pipeName = pipeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignOffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignOffResponse", Namespace="http://www.lionth.com/", Order=0)]
        public Alive.Test.CommunicationServer.Communication.SignOffResponseBody Body;
        
        public SignOffResponse() {
        }
        
        public SignOffResponse(Alive.Test.CommunicationServer.Communication.SignOffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SignOffResponseBody {
        
        public SignOffResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommunicationServiceSoapChannel : Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommunicationServiceSoapClient : System.ServiceModel.ClientBase<Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap>, Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap {
        
        public CommunicationServiceSoapClient() {
        }
        
        public CommunicationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommunicationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alive.Test.CommunicationServer.Communication.SendMessageResponse Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap.SendMessage(Alive.Test.CommunicationServer.Communication.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public bool SendMessage(string pipeName, string message) {
            Alive.Test.CommunicationServer.Communication.SendMessageRequest inValue = new Alive.Test.CommunicationServer.Communication.SendMessageRequest();
            inValue.Body = new Alive.Test.CommunicationServer.Communication.SendMessageRequestBody();
            inValue.Body.pipeName = pipeName;
            inValue.Body.message = message;
            Alive.Test.CommunicationServer.Communication.SendMessageResponse retVal = ((Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alive.Test.CommunicationServer.Communication.SendMessageToGroupResponse Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap.SendMessageToGroup(Alive.Test.CommunicationServer.Communication.SendMessageToGroupRequest request) {
            return base.Channel.SendMessageToGroup(request);
        }
        
        public int SendMessageToGroup(string groupName, string message) {
            Alive.Test.CommunicationServer.Communication.SendMessageToGroupRequest inValue = new Alive.Test.CommunicationServer.Communication.SendMessageToGroupRequest();
            inValue.Body = new Alive.Test.CommunicationServer.Communication.SendMessageToGroupRequestBody();
            inValue.Body.groupName = groupName;
            inValue.Body.message = message;
            Alive.Test.CommunicationServer.Communication.SendMessageToGroupResponse retVal = ((Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap)(this)).SendMessageToGroup(inValue);
            return retVal.Body.SendMessageToGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alive.Test.CommunicationServer.Communication.GetMessageResponse Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap.GetMessage(Alive.Test.CommunicationServer.Communication.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public Alive.Test.CommunicationServer.Communication.ArrayOfString GetMessage(string pipeName) {
            Alive.Test.CommunicationServer.Communication.GetMessageRequest inValue = new Alive.Test.CommunicationServer.Communication.GetMessageRequest();
            inValue.Body = new Alive.Test.CommunicationServer.Communication.GetMessageRequestBody();
            inValue.Body.pipeName = pipeName;
            Alive.Test.CommunicationServer.Communication.GetMessageResponse retVal = ((Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap)(this)).GetMessage(inValue);
            return retVal.Body.GetMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alive.Test.CommunicationServer.Communication.RegisterResponse Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap.Register(Alive.Test.CommunicationServer.Communication.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public void Register(string pipeName) {
            Alive.Test.CommunicationServer.Communication.RegisterRequest inValue = new Alive.Test.CommunicationServer.Communication.RegisterRequest();
            inValue.Body = new Alive.Test.CommunicationServer.Communication.RegisterRequestBody();
            inValue.Body.pipeName = pipeName;
            Alive.Test.CommunicationServer.Communication.RegisterResponse retVal = ((Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap)(this)).Register(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alive.Test.CommunicationServer.Communication.RegisterWithGroupResponse Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap.RegisterWithGroup(Alive.Test.CommunicationServer.Communication.RegisterWithGroupRequest request) {
            return base.Channel.RegisterWithGroup(request);
        }
        
        public void RegisterWithGroup(string pipeName, string groupName) {
            Alive.Test.CommunicationServer.Communication.RegisterWithGroupRequest inValue = new Alive.Test.CommunicationServer.Communication.RegisterWithGroupRequest();
            inValue.Body = new Alive.Test.CommunicationServer.Communication.RegisterWithGroupRequestBody();
            inValue.Body.pipeName = pipeName;
            inValue.Body.groupName = groupName;
            Alive.Test.CommunicationServer.Communication.RegisterWithGroupResponse retVal = ((Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap)(this)).RegisterWithGroup(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alive.Test.CommunicationServer.Communication.SignOffResponse Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap.SignOff(Alive.Test.CommunicationServer.Communication.SignOffRequest request) {
            return base.Channel.SignOff(request);
        }
        
        public void SignOff(string pipeName) {
            Alive.Test.CommunicationServer.Communication.SignOffRequest inValue = new Alive.Test.CommunicationServer.Communication.SignOffRequest();
            inValue.Body = new Alive.Test.CommunicationServer.Communication.SignOffRequestBody();
            inValue.Body.pipeName = pipeName;
            Alive.Test.CommunicationServer.Communication.SignOffResponse retVal = ((Alive.Test.CommunicationServer.Communication.CommunicationServiceSoap)(this)).SignOff(inValue);
        }
    }
}
